# Default config
resample_factor = 16
name = "default"
dataset_path = "~/data/denoise/charge_density/x{resample_factor}"
output_path = "~/data/denoise/conserv/{name}"
plots_path = "{output_path}/plots"
sample_file_name="background_density10_negative_10kV_claw0021.hdf"
sample_file_path = "{dataset_path}/original/{sample_file_name}"
noisy_samples = "noisy_50"
model_weights = "{output_path}/checkpoint.hdf5"
training_log = "{output_path}/training.csv"
cylindrical = true

workers = 4
seed = 2021
training_batch = 4
loss = "mse"
optimizer = "Adam"
epochs = 1000
fit_verbose = 2

[zero_patch]
height = 2400
width = 320
scale_with_resample = true
