# These are the parameters used to train the charge-conserving model

# Resample factor. If >1, the data is downsampled.
resample_factor = 1

# Location of the training dataset
dataset_path = "~/data/denoise/charge_density_2x"

# Sub-folder within dataset_path where the noisy samples are stored
noisy_samples = "noisy_10"

sample_file_name="background_density12_negative_15kV_claw0018.hdf"

# No. of tensorflow workers
workers = 1

# Batch size
training_batch = 4

# Regularization / loss function
loss = "bykernel"

# Size of convolution charge-conserving kernels is 2l+1
l = 6

# Size of the convolutions in the partition network.
m = 4

# scaling of the fft regularization
alpha = 100.0

filters=12

# Charge weight factor for the loss function (denoted as w in the paper).
weight_factor = 0.025

clipvalue=100.0

# Initial learning rate
init_learning_rate = 0.000001
